### PR TITLE
fix: Add warn log for create/update interval

### LINKED ISSUE #4586: CPU increases abnormal when creating interval with us/ns unit
# 🐞 Bug Report

### Affected Services [**REQUIRED**]

 The issue is located in: support-scheduler

### Is this a regression?

 No

### Description and Minimal Reproduction [**REQUIRED**]
1. Deploy EdgeX
2. Create interval with us/ns
```
POST http://localhost:59861/api/v3/interval
[
   {
      "interval":{
         "name":"interval_1679737508110",
         "start":"20230605T094508",
         "interval":"1us"
      },
      "apiVersion":"v3"
   }
]
```

## 🔥 Exception or Error
<pre><code>
Status code: 503
Response body: HTTP request timeout
CPU: more than 200% (view CPU by "docker stats")

</code></pre>

## 🌍  Your Environment
**Deployment Environment:** Ubuntu 22.04 / x86

**EdgeX Version [**REQUIRED**]:** Main

**Anything else relevant?**

### PR DESCRIPTION
**Pull request by lindseysimple**
Add warn log for interval value from Interval and AutoEvent if the value is too small.

Closes #4586.

### CODE REVIEW

**Comment by lindseysimple** [comment]
@cloudxxx8 would you please take an initial look before pushing to community, thanks.

File: internal/core/metadata/application/device.go [hunk 1]
```diff
@@ -63,6 +67,16 @@ func AddDevice(d models.Device, ctx context.Context, dic *di.Container) (id stri
 		correlation.FromContext(ctx),
 	)
 
+	// If device is successfully created, check each AutoEvent interval value and display a warning if it's smaller than the suggested 10ms value
+	for _, autoEvent := range d.AutoEvents {
+		valid, err := utils.CheckDuration(autoEvent.Interval, minAutoEventInterval)
+		if err != nil {
+			lc.Warnf("failed to check auto event interval: %v", err)
+		} else if !valid {
+			lc.Warnf("the interval value '%s' is smaller than the suggested value '%s', which might cause abnormal CPU increase", autoEvent.Interval, minAutoEventInterval)
```
Comment (cloudxxx8) [inline internal/core/metadata/application/device.go]: since the log message is the same, move the warning log to the checking fucntion.

File: internal/core/metadata/application/device.go [hunk 2]
```diff
@@ -63,6 +67,16 @@ func AddDevice(d models.Device, ctx context.Context, dic *di.Container) (id stri
 		correlation.FromContext(ctx),
 	)
 
+	// If device is successfully created, check each AutoEvent interval value and display a warning if it's smaller than the suggested 10ms value
+	for _, autoEvent := range d.AutoEvents {
+		valid, err := utils.CheckDuration(autoEvent.Interval, minAutoEventInterval)
+		if err != nil {
+			lc.Warnf("failed to check auto event interval: %v", err)
```
Comment (cloudxxx8) [inline internal/core/metadata/application/device.go]: if there is anything parsing wrong, it should log as error.
this part should be moved into the checking function.

File: internal/pkg/utils/time.go [hunk 3]
```diff
@@ -0,0 +1,32 @@
...
+import (
+	"fmt"
+	"time"
+
+	"github.com/edgexfoundry/go-mod-core-contracts/v3/errors"
+)
+
+// CheckDuration parses the ISO 8601 time duration string to Duration type
+// and evaluates if the duration value is smaller than the suggested minimum duration string
+func CheckDuration(value string, min string) (bool, errors.EdgeX) {
```
Comment (cloudxxx8) [inline internal/pkg/utils/time.go]: rename to `CheckMinInterval`, because it's not general for all kinds of Duration check, and it doesn't need to return error.
Keep the bool return value for unit test, but the caller can ignore it.

**Review by cloudxxx8 — CHANGES_REQUESTED** [review]

**Comment by lindseysimple** [comment]
Change has been done to address all the comments, thanks.

**Review by cloudxxx8 — APPROVED** [review]
LGTM
